import { Button } from "../Elements/Button";
import { ButtonSettings } from "../../../components/selectors/Settings/ButtonSettings";

Button.craft = {
  displayName: "Botão",
  props: {
    marginTop: "5px",
    marginRight: "0px",
    marginLeft: "0px",
    marginBottom: "5px",
    paddingTop: "10px",
    paddingRight: "10px",
    paddingLeft: "10px",
    paddingBottom: "10px",
    width: "50%",
    display: "flex",
    background: "#5D58E8",
    borderWidth: "0px",
    borderRadius: "5px",
    cursor: "pointer",
    className: "icon-button",
    type: "button",
    text: "Quero saber mais",
    notDeletable: false,
    additional_css: "",
    fontFamily: "sans-serif",
    fontWeight: "400",
    fontSize: "16px",
    textTransform: "none",
    fontStyle: "normal",
    textDecoration: "none",
    wordSpacing: "0",
    letterSpacing: "0",
    boxShadow: "none",
    lineHeight: "0px",
    boxShadowString: "none",
    borderStyle: "none",
    borderTopWidth: "0px",
    borderRightWidth: "0px",
    borderBottomWidth: "0px",
    borderLeftWidth: "0px",
    borderColor: "transparent",
    borderTopLeftRadius: "0px",
    borderTopRightRadius: "0px",
    borderBottomRightRadius: "0px",
    borderBottomLeftRadius: "0px",

    minHeight: "100px",
    flexDirection: "column",
    justifyContent: "start",
    alignItems: "start",
    rowGap: "0",
    columnGap: "0",
    flexWrap: "wrap",

    mobileWidth: "100%",
    mobileMinHeight: "100px",
    mobileFlexDirection: "column",
    mobileJustifyContent: "start",
    mobileAlignItems: "start",
    mobileRowGap: "0",
    mobileColumnGap: "0",
    mobileFlexWrap: "wrap",
    mobileMarginTop: "0",
    mobileMarginRight: "0",
    mobileMarginLeft: "0",
    mobileMarginBottom: "0",
    mobilePaddingTop: "2",
    mobilePaddingRight: "2",
    mobilePaddingLeft: "2",
    mobilePaddingBottom: "2",
    mobileAlignSelf: "initial",
    mobileFlexOrder: "0",
    mobileFlexShrink: "1",
    mobileFlexGrow: "0",
    mobilePosition: "static",
    mobileTop: "0",
    mobileLeft: "0",
    mobileRight: "0",
    mobileBottom: "0",
    mobileZIndex: "0",
  },
  related: {
    settings: ButtonSettings,
  },
};

export default Button;
