import { CountdownSettings } from "../Settings/CountdownSettings";
import { Countdown } from "../Elements/Countdown";

Countdown.craft = {
  displayName: "Contador regressivo",

  props: {
    //element props countdown geral
    background: "#2196F3",
    borderStyle: "none",
    endDate: "2024-05-25T21:02:00Z",
    CountType: "weekly_diary",
    displayWeekly: "monday",
    customText: "false",
    displayFormatDays: "true",
    displayFormatHours: "true",
    displayFormatMin: "true",
    displayFormatSeconds: "true",
    timezone: "-03:00",
    showAction: "hide",
    gap: "10px",
    gapMobile: "10px",
    // minWidthMobile: "28%",
    // minWidth: "20%",
    maxWidth: "70%",
    maxWidthMobile: "22%",
    //element estilo props countdown text
    textDays: "Dias",
    textHours: "Horas",
    textMinutes: "Minutos",
    textSeconds: "Segundos",
    fontSizeText: "20px",
    mobileFontSizeText: "12px",
    fontFamilyText: "sans-serif",
    colorText: "#FFFFFF",
    fontWeightText: "400",
    textAlignText: "left",
    fontStyleText: "normal",
    textDecorationText: "none",
    lineHeightText: "1.5",
    mobileLineHeightText: "1.5",
    letterSpacingText: "0",
    mobileLetterSpacingText: "0",

    alignSelfText: "center",
    //element estilo props countdown timer
    timerSeconds: "00",
    timerDays: "10",
    timerHours: "01",
    timerMinutes: "10",
    letterSpacing: "0",
    mobileLetterSpacing: "0",
    color: "#FFFFFF",
    fontSize: "34px",
    mobileFontSize: "34px",
    fontWeight: "400",
    mobileLineHeight: "1.5",
    textAlign: "left",
    lineHeight: "1.5",
    fontFamily: "sans-serif",
    textTransform: "none",
    fontStyle: "normal",
    textDecoration: "none",
    // element props
    marginTop: "0px",
    marginRight: "0px",
    marginLeft: "0px",
    marginBottom: "0px",
    paddingTop: "10px",
    paddingRight: "20px",
    paddingLeft: "20px",
    paddingBottom: "10px",
    alignSelf: "center",

    order: "1",
    position: "static",
    top: "0",
    left: "0",
    right: "0",
    bottom: "0",
    zIndex: "0",
    justifyContent: "center",
    mobileJustifyContent: "center",
    mobileMarginTop: "0px",
    mobileMarginRight: "0px",
    mobileMarginLeft: "0px",
    mobileMarginBottom: "0px",
    mobilePaddingTop: "0px",
    mobilePaddingRight: "0px",
    mobilePaddingLeft: "0px",
    mobilePaddingBottom: "0px",
    mobileAlignSelf: "center",
    mobileOrder: "1",
    mobilePosition: "static",
    mobileTop: "0",
    mobileLeft: "0",
    mobileRight: "0",
    mobileBottom: "0",
    mobileZIndex: "0",
    //border
    borderTopLeftRadius: "5px",
    borderTopRightRadius: "5px",
    borderBottomRightRadius: "5px",
    borderBottomLeftRadius: "5px",
    borderColor: "rgba(0,0,0,0.1)",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",

    hidden: false,
    mobileHidden: false,
  },
  related: {
    settings: CountdownSettings,
  },
};

export default Countdown;
