import { Grid } from "../Elements/Grid";
import { GridSettings } from "../Settings/GridSettings";

Grid.craft = {
  displayName: "Grid",
  props: {
    maxWidth: "100%",
    display: "grid",
    // gridTemplateRows: "repeat(2, 100px)",
    // gridTemplateColumns: "repeat(2, auto",

    gridColumns: 3,
    gridRows: 2,

    width: "100%",
    minHeight: "100px",
    rowGap: "5px",
    columnGap: "5px",

    flexWrap: "nowrap",
    htmlTag: "div",
    url: "",
    backgroundColor: "transparent",
    backgroundImage: "",
    borderStyle: "none",
    borderTopWidth: "0px",
    borderRightWidth: "0px",
    borderBottomWidth: "0px",
    borderLeftWidth: "0px",
    borderColor: "transparent",
    borderTopLeftRadius: "0px",
    borderTopRightRadius: "0px",
    borderBottomRightRadius: "0px",
    borderBottomLeftRadius: "0px",
    hoverBorderStyle: "none",
    hoverBorderTopWidth: "10px",
    hoverBorderRightWidth: "0px",
    hoverBorderBottomWidth: "0px",
    hoverBorderLeftWidth: "0px",
    hoverBorderColor: "transparent",
    hoverBorderTopLeftRadius: "0px",
    hoverBorderTopRightRadius: "0px",
    hoverBorderBottomRightRadius: "0px",
    hoverBorderBottomLeftRadius: "0px",
    hoverBackgroundColor: "transparent",
    backgroundcolorTransitionDuration: "0.3",
    borderTransitionDuration: "0.3",
    marginTop: "0",
    marginRight: "0",
    marginLeft: "0",
    marginBottom: "0",
    paddingTop: "2",
    paddingRight: "2",
    paddingLeft: "2",
    paddingBottom: "2",
    alignSelf: "initial",
    flexOrder: "0",
    flexShrink: "1",
    flexGrow: "0",
    position: "static",
    top: "0",
    left: "0",
    right: "0",
    bottom: "0",
    zIndex: "0",
    mobileWidth: "100%",
    mobileMinHeight: "100px",
    mobileFlexDirection: "column",
    mobileJustifyContent: "start",
    mobileAlignItems: "start",
    mobileRowGap: "0",
    mobileColumnGap: "0",
    mobileFlexWrap: "wrap",
    mobileMarginTop: "0",
    mobileMarginRight: "0",
    mobileMarginLeft: "0",
    mobileMarginBottom: "0",
    mobilePaddingTop: "2",
    mobilePaddingRight: "2",
    mobilePaddingLeft: "2",
    mobilePaddingBottom: "2",
    mobileAlignSelf: "initial",
    mobileFlexOrder: "0",
    mobileFlexShrink: "1",
    mobileFlexGrow: "0",
    mobilePosition: "static",
    mobileTop: "0",
    mobileLeft: "0",
    mobileRight: "0",
    mobileBottom: "0",
    mobileZIndex: "0",
  },
  rules: {
    canDrag: () => true,
  },
  related: {
    settings: GridSettings,
  },
};

export default Grid;
